// <auto-generated />
namespace FIT5032_Assignment_30533651.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BookCoursesModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BookCoursesModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202010230421483_BookCoursesModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
